#!/bin/sh
if [ -t 1 ]; then
  . "$(dirname "$0")/_/husky.sh"
  cd "$(dirname "$0")/.." &&  exec < /dev/tty && npx cz --hook --yes || true
else
  echo "Skipping Commitizen interactive prompt as no TTY is available."
fi